import type { Metadata } from "next";
import { Geist, Geist_Mono, Press_Start_2P, Space_Grotesk } from "next/font/google";
import "./globals.css";

const spaceGro = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const p2pfont = Press_Start_2P({
  variable: "--font-press-start",
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${p2pfont.className} ${spaceGro.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
